version: '3.8'

services:
  sqlserver:
    image: ://microsoft.com
    container_name: sql_universidad_container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Demi1234!
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
